# Generated by Django 5.0.6 on 2024-06-09 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_column='USERNAME', max_length=200)),
                ('password', models.CharField(db_column='PASSWORD', max_length=200)),
                ('email', models.CharField(db_column='EMAIL', unique=True)),
                ('address', models.JSONField(db_column='ADDRESS')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_staff', models.BooleanField(db_column='IS_STAFF', default=False)),
            ],
            options={
                'verbose_name': 'USER',
                'verbose_name_plural': 'USERS',
                'db_table': 'USERS',
            },
        ),
    ]
